dist: xenial
sudo: required

language: python
python:
  - 3.7
  - 3.8
before_install:
  - pip install codecov
  - pip install poetry
install:
  - poetry install -E aiohttp_backend
script: poetry run make check
after_success: codecov
notifications:
  email: false