name: Test And Lint package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v7
        with:
          poetry-version: 1.2.0
      - run: make install-deps
      - run: make lint
        if: matrix.python-version == 3.10
      - run: poetry lock --check
        if: matrix.python-version == 3.10
      - run: make test
      - uses: codecov/codecov-action@v3
        if: matrix.python-version == 3.10
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
