name: Test And Lint package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: 1.4.0
      - run: make install-deps
      - run: make lint
        if: matrix.python-version == 3.11
      - run: poetry lock --check
        if: matrix.python-version == 3.11
      - run: make test
      - uses: codecov/codecov-action@v4
        if: matrix.python-version == 3.11
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
